name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        cd Example
        pod install
      shell: bash
    - name: Lint podspec file
      uses: ./.github/actions/cocoapods-action
      with:
        additional_lint_params: --private
        scheme: GitHubActionPodDemo-Example
