name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Lint podspec file
      uses: ./.github/actions/cocoapods-action
      with:
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
        scheme: GitHubActionPodDemo-Example
        additional_lint_params: --private
