name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@master
    - name: Lint podspec file
      uses: ./.github/actions/cocoapods-action
